import type { EquipmentDef } from "./types";

// ============================================================
// TOP DRIVE — per K-CW-EM-GU-044
// Equipment Code TDRT-313-020, KCAD Class 6157, Criticality: Category A
// ============================================================
export const TOPDRIVE: EquipmentDef = {
  id: "topdrive",
  name: "Top Drive",
  docRef: "K-CW-EM-GU-044",
  equipmentCode: "TDRT-313-020",
  kcadClass: "6157",
  criticality: "Category A",
  standards: ["API Spec 8C", "API RP 8B", "API Spec 7-1", "API Spec 7-2"],
  config: [
    { key: "manufacturer", label: "Manufacturer", options: ["NOV / Varco TDS", "Bentec", "Canrig", "Tesco", "Other"] },
    { key: "motorType", label: "Motor type", options: ["AC Electric", "DC Electric"] },
    { key: "carriageType", label: "Carriage type", options: ["Fixed", "Retractable"] },
    { key: "guideBeam", label: "Guide beam", options: ["Mono-Rail", "Dual-Rail"] },
    { key: "hydraulicSys", label: "Hydraulic system", options: ["On-board HPU", "External / off-board HPU"] },
  ],
  frequencies: [
    { id: "td_daily", label: "Daily", cat: "I", who: "Rig personnel", inherits: [], desc: "Visual check entire unit, oil levels, wash pipe, IBOP, link tilt, service loops, lubrication." },
    { id: "td_weekly", label: "Weekly", cat: "II", who: "Senior maintenance / Toolpusher", inherits: [], desc: "Component check for damage/wear, function test of operations/alarms/interlocks, hydraulics, lubrication." },
    { id: "td_monthly", label: "Monthly", cat: "II", who: "Senior maintenance / Toolpusher", inherits: [], desc: "Elevator link diameter, counter balance chain, motor brake, shot pin, IBOP splines, link tilt bushings." },
    { id: "td_quarterly", label: "Quarterly", cat: "II", who: "Senior maintenance / Toolpusher", inherits: [], desc: "Accumulator pre-charge, gearbox oil filter, hydraulic filter, motor lubrication, encoder belt." },
    { id: "td_halfyear", label: "Half-yearly", cat: "III", who: "OEM / 3rd party / authorized KCAD personnel", inherits: [], desc: "Main shaft axial movement, gear backlash, oil change, load path visual/NDT, electrical cabinet." },
    { id: "td_yearly", label: "Yearly", cat: "III", who: "OEM / 3rd party / authorized KCAD personnel", inherits: [], desc: "Full assessment incl. hydraulic oil change, bail pin NDT, gooseneck UT, load collar disassembly, elevator link measurement." },
    { id: "td_ibop", label: "Yearly IBOP", cat: "IV", who: "OEM / qualified 3rd party on approved list", inherits: [], desc: "Major inspection and recertification of IBOP. Exchange with certified unit." },
    { id: "td_5yearly", label: "5-yearly / 15k hrs", cat: "IV", who: "OEM / qualified 3rd party on approved list", inherits: [], desc: "Major inspection and recertification / overhaul per API RP 8B. Also triggered at 15,000 operating hours (max 7 years).", special: "cativ" },
  ],
  sections: {
    td_daily: [
      { id: "tdd_clean", name: "Daily — General", items: [
        { id: "tdd1", description: "Clean unit as necessary", methods: ["Clean"] },
        { id: "tdd2", description: "Visual check entire unit for cracks, loose fits or connections, elongation, signs of wear, corrosion or overloading", methods: ["VT"], critical: true },
        { id: "tdd3", description: "Visual check and verify proper operation of Top Drive", methods: ["VT", "Func"] },
      ]},
      { id: "tdd_oil", name: "Daily — Oil & hydraulics", items: [
        { id: "tdd4", description: "Visual check gearbox and hydraulic reservoir oil level", methods: ["VT"], critical: true },
        { id: "tdd5", description: "Visual check hydraulic and gear oil filter indicators or gauges", methods: ["VT"] },
        { id: "tdd6", description: "Visual check hydraulic pressure and return pressure on HPU if applicable", methods: ["VT"] },
      ]},
      { id: "tdd_comp", name: "Daily — Components", items: [
        { id: "tdd7", description: "Visual check wash pipe assembly for leaks", methods: ["VT"], critical: true },
        { id: "tdd8", description: "Visual check link tilt clamps position and tightness", methods: ["VT"] },
        { id: "tdd9", description: "Visual check link tilt hydraulics and pin connections for leaks and wear", methods: ["VT"] },
        { id: "tdd10", description: "Visual check IBOP actuator cylinder for leaks", methods: ["VT"] },
        { id: "tdd11", description: "Visual check upper and lower IBOP valves for proper operation", methods: ["VT", "Func"], critical: true },
        { id: "tdd12", description: "Visual check tool joint lock screws for proper torque", methods: ["VT"] },
        { id: "tdd13", description: "Visual check torque back-up / torque wrench cylinder for correct operation, wear and leaks", methods: ["VT", "Func"] },
        { id: "tdd14", description: "Visual check clamp position and status of tong dies", methods: ["VT"] },
        { id: "tdd15", description: "Visual check service loops for damage", methods: ["VT"] },
        { id: "tdd16", description: "Visual check controls, alarms, safety interlocks and indicator lamps", methods: ["VT", "Func"], critical: true },
        { id: "tdd17", description: "Check during operation: motor housing for excess heat build-up; listen for grinding or knocking noises", methods: ["VT"] },
        { id: "tdd18", description: "Visually check guide beam and related equipment for proper condition", methods: ["VT"] },
      ]},
      { id: "tdd_lube", name: "Daily — Lubrication", items: [
        { id: "tdd20", description: "Lubricate wash pipe assembly", methods: ["Lube"] },
        { id: "tdd21", description: "Lubricate upper main body oil seal grease fittings and quill shaft bearing if applicable", methods: ["Lube"] },
        { id: "tdd22", description: "Lubricate shot pin assembly gear teeth", methods: ["Lube"] },
        { id: "tdd23", description: "Lubricate rotating link adapter gear teeth", methods: ["Lube"] },
        { id: "tdd24", description: "Lubricate torque back-up clamp / torque wrench as applicable", methods: ["Lube"] },
        { id: "tdd25", description: "Lubricate IBOP actuator yoke, pins and cranks (TDS-3&4 and IDS 1 only)", methods: ["Lube"] },
        { id: "tdd26", description: "Lubricate stabilizer bushing", methods: ["Lube"] },
        { id: "tdd27", description: "Lubricate guide roller bearings / glide surfaces (only if rig in tripping operation)", methods: ["Lube"] },
      ]},
    ],
    td_weekly: [
      { id: "tdw_vis", name: "Weekly — Visual & function checks", items: [
        { id: "tdw1", description: "Visual check entire unit for corrosion, deformation, loose or missing components, deterioration, proper lubrication, visible external cracks, and adjustment", methods: ["VT"], critical: true },
        { id: "tdw2", description: "Visual check motor alignment cylinder", methods: ["VT"] },
        { id: "tdw3", description: "Visual check lubrication oil spray and flow", methods: ["VT"] },
        { id: "tdw4", description: "Visual check AC drilling motor louvers for damage, loose parts or blockage", methods: ["VT"] },
        { id: "tdw5", description: "Visual check guide dolly including roller- and slide components", methods: ["VT"] },
        { id: "tdw6", description: "Visual check torque back-up clamp / torque wrench cylinder tong die for wear", methods: ["VT", "Dim"] },
        { id: "tdw7", description: "Visual check stabbing guides and arms for damage and wear", methods: ["VT"] },
        { id: "tdw8", description: "Visual check link tilt assembly for worn components and correct setting if applicable", methods: ["VT"] },
        { id: "tdw9", description: "Visual check function and condition of counter balance system and landing collar", methods: ["VT", "Func"] },
        { id: "tdw10", description: "Check air regulator / lubricator / filter for correct operation and setting if applicable", methods: ["VT", "Func"] },
        { id: "tdw11", description: "Visual check louvers for electric motors (air-intake and outlet) — clean as required", methods: ["VT", "Clean"] },
        { id: "tdw12", description: "Visually inspect cooling system for proper operation", methods: ["VT"] },
        { id: "tdw13", description: "Visual check dolly rollers or slide pads for damage and wear", methods: ["VT", "Dim"] },
        { id: "tdw14", description: "Visually inspect gimbal and torque tube for excessive radial or axial play", methods: ["VT"] },
        { id: "tdw15", description: "Visual check drive motor cables and service loops for damage", methods: ["VT"] },
        { id: "tdw16", description: "Visually inspect hydraulic system for leaks, damaged hose covers, kinked or crushed hose — tighten or replace leaking connections, clean dirt from hydraulic components", methods: ["VT"], critical: true },
      ]},
      { id: "tdw_lube", name: "Weekly — Lubrication", items: [
        { id: "tdw20", description: "Lubricate stabilizer bushing", methods: ["Lube"] },
        { id: "tdw21", description: "Lubricate stabilizer liner", methods: ["Lube"] },
        { id: "tdw22", description: "Lubricate rotating link adapter grease fittings", methods: ["Lube"] },
        { id: "tdw23", description: "Lubricate torque arrestor tube, unpainted surfaces", methods: ["Lube"] },
        { id: "tdw24", description: "Lubricate IBOP actuator rollers, crank and upper IBOP-valve (TDS 8, 9, 10, 11)", methods: ["Lube"] },
        { id: "tdw25", description: "Lubricate guide dolly or slide pads as applicable", methods: ["Lube"] },
        { id: "tdw26", description: "Lubricate bail pins as applicable", methods: ["Lube"] },
        { id: "tdw27", description: "Lubricate link tilt crank pivot pin and stop", methods: ["Lube"] },
        { id: "tdw28", description: "Lubricate elevator support and master bushing wear guide", methods: ["Lube"] },
        { id: "tdw29", description: "Lubricate torque arrestor tubes, clamp cylinder gate and rotating link adapter", methods: ["Lube"] },
        { id: "tdw30", description: "Lubricate upper and lower main body seal as applicable", methods: ["Lube"] },
      ]},
      { id: "tdw_bentec", name: "Weekly — Bentec-specific lubrication", requires: { manufacturer: "Bentec" }, items: [
        { id: "tdwb1", description: "Grease link adapter suspension points for elevator links (B)", methods: ["Lube"] },
        { id: "tdwb2", description: "Brush pipe grease onto the pipe handler bearings (B)", methods: ["Lube"] },
        { id: "tdwb3", description: "Lubricate link adapter bearing (B)", methods: ["Lube"] },
        { id: "tdwb4", description: "Lubricate pipe handler ball joint and stop guide (B)", methods: ["Lube"] },
        { id: "tdwb5", description: "Lubricate suspension point on the yoke (B)", methods: ["Lube"] },
        { id: "tdwb6", description: "Lubricate the upper transmission gasket (B)", methods: ["Lube"] },
        { id: "tdwb7", description: "Lubricate transmission trunnion (B)", methods: ["Lube"] },
      ]},
    ],
    td_monthly: [
      { id: "tdm_main", name: "Monthly — Detailed component check", items: [
        { id: "tdm1", description: "Check upper stem liner for corrosion or if wash pipe packing is serviced", methods: ["VT"] },
        { id: "tdm2", description: "Check counter balance chain assembly components", methods: ["VT"] },
        { id: "tdm3", description: "Clean residual mud from inside the bonnet", methods: ["Clean"] },
        { id: "tdm4", description: "Check drilling motor brake for correct operation and wear", methods: ["VT", "Func"], critical: true },
        { id: "tdm5", description: "Check drilling motor for smooth running and no excessive vibration", methods: ["VT", "Vib"] },
        { id: "tdm7", description: "Check air exhaust mufflers — clean or replace as required", methods: ["VT", "Clean"] },
        { id: "tdm8", description: "Clean heat exchanger if applicable", methods: ["Clean"] },
        { id: "tdm9", description: "Check gearbox breather — ensure not plugged", methods: ["VT"] },
        { id: "tdm10", description: "Check shot pin group for correct operation and wear", methods: ["VT", "Func"] },
        { id: "tdm11", description: "Inspect link tilt bushings, clamps and actuator cylinder clevis pins for wear", methods: ["VT", "Dim"] },
        { id: "tdm12", description: "Visually check link eye diameter", methods: ["VT", "Dim"], critical: true },
        { id: "tdm13", description: "Visually check stabilizer liners for wear", methods: ["VT"] },
        { id: "tdm14", description: "Check torque arrestor securing pins to rotating head for wear and proper lubrication", methods: ["VT"] },
        { id: "tdm15", description: "Check IBOP actuator yoke bushings and pins for excessive play", methods: ["VT", "Dim"] },
        { id: "tdm16", description: "Check IBOP actuator rollers for wear and free movement", methods: ["VT"] },
        { id: "tdm17", description: "Inspect IBOP splines for damage (TDS-3&4 and IDS 1)", methods: ["VT"] },
        { id: "tdm18", description: "Check torque back-up clamp / torque wrench cylinder gate hinge pins for wear", methods: ["VT", "Dim"] },
        { id: "tdm19", description: "Check stabbing guide for ring of master bushing wear guide (if installed)", methods: ["VT"] },
        { id: "tdm20", description: "Check all electrical lines, connectors and related hardware for integrity", methods: ["VT", "Elec"] },
        { id: "tdm21", description: "Check to ensure all lubrication points are well lubricated", methods: ["Lube"] },
      ]},
    ],
    td_quarterly: [
      { id: "tdq_main", name: "Quarterly — Accumulators, filters & motors", items: [
        { id: "tdq1", description: "Check nitrogen pre-charge on accumulators", methods: ["VT"], measurement: true, unit: "bar" },
        { id: "tdq2", description: "Check gearbox oil filter indicators or gauges — replace or clean filter as required", methods: ["VT", "Clean"] },
        { id: "tdq3", description: "Check hydraulic system filter indicators or gauges — replace filter as required", methods: ["VT", "Clean"] },
        { id: "tdq4", description: "Lubricate AC drilling motor and blower motor per OEM recommendation", methods: ["Lube"] },
        { id: "tdq5", description: "Check encoder for proper belt tightness if applicable", methods: ["VT"] },
      ]},
    ],
    td_halfyear: [
      { id: "tdh_main", name: "Half-yearly — Main shaft, gears & load path", items: [
        { id: "tdh1", description: "Measure and document main shaft axial movement (end play) and check bore wear", methods: ["Dim"], measurement: true, unit: "mm", critical: true },
        { id: "tdh2", description: "Inspect gears for backlash and check gear teeth for pitting or corrosive wear", methods: ["VT", "Dim"], critical: true },
        { id: "tdh3", description: "Change gear oil and filter", methods: ["Lube"] },
        { id: "tdh4", description: "Close visual inspection of lubrication oil spray and flow", methods: ["VT"] },
        { id: "tdh5", description: "Check hydraulic oil and filter for cleanliness — replace accordingly", methods: ["VT", "Lube"] },
        { id: "tdh6", description: "Visual inspection for corrosion, deformation, deterioration, visible external cracks of critical areas in the primary load path — NDT as required", methods: ["VT", "NDT"], critical: true, ndt: true },
        { id: "tdh7", description: "Test operation of low oil level / pressure alarm(s)", methods: ["Func"], critical: true },
        { id: "tdh8", description: "Check proximity probe or magnetic pick-up cables", methods: ["Elec"] },
        { id: "tdh9", description: "Test purge air differential pressure switch setting as applicable", methods: ["Func"] },
        { id: "tdh10", description: "Close visual check of main electrical cabinet and junction boxes", methods: ["VT", "Elec"] },
      ]},
    ],
    td_yearly: [
      { id: "tdy_gen", name: "Yearly — General assessment & hydraulics", items: [
        { id: "tdy1", description: "Carry out a general assessment of condition including a function test", methods: ["VT", "Func"], critical: true },
        { id: "tdy2", description: "Change hydraulic oil and filters for on-board hydraulic units", methods: ["Lube"] },
        { id: "tdy3", description: "Perform oil analysis for off-board hydraulic unit — change oil per lab results", methods: ["Lab", "Lube"] },
        { id: "tdy4", description: "Change hydraulic filters and check magnet on drain plug for metal particles", methods: ["VT", "Lube"] },
        { id: "tdy5", description: "Renew reservoir breather", methods: ["Lube"] },
        { id: "tdy6", description: "Inspect entire hydraulic unit for electrical and mechanical integrity and correct settings", methods: ["VT", "Elec", "Func"] },
      ]},
      { id: "tdy_bail", name: "Yearly — Bail pins & bail arm (NDT)", items: [
        { id: "tdy10", description: "Check upper bearing retainer O-ring, bearing isolator and oil seal for wear — replace as required", methods: ["VT"] },
        { id: "tdy11", description: "Check bail pins for wear by jacking bail arm up and down — measure and record movement with dial indicator", methods: ["Dim"], measurement: true, unit: "mm", critical: true },
        { id: "tdy12", description: "Remove bail pins as required — measure and record pin and bore dimensions inclusive NDT inspection", methods: ["Dim", "NDT"], measurement: true, unit: "mm", critical: true, ndt: true },
        { id: "tdy13", description: "Check bail in way of pins for signs of damage and cracks — rotate bail each way for inspection", methods: ["VT", "NDT"], critical: true },
        { id: "tdy14", description: "Inspect and measure bail arm top wear point (bail radius) — record results and compare with OEM maximum allowable wear — carry out NDT", methods: ["Dim", "NDT"], measurement: true, unit: "mm", critical: true, ndt: true },
      ]},
      { id: "tdy_shaft", name: "Yearly — Main shaft, load collar & gooseneck", items: [
        { id: "tdy20", description: "Using dial indicator measure play in top bearing — record results — adjust shimming per OEM recommendation if necessary", methods: ["Dim"], measurement: true, unit: "mm" },
        { id: "tdy21", description: "Measure wall thickness at gooseneck on specific points every 20–30cm — record readings and compare with OEM wear limits", methods: ["UT"], measurement: true, unit: "mm", critical: true },
        { id: "tdy22", description: "Disassemble and inspect visually load / landing collar and lower main shaft for wear, damage, corrosion, deformation, deterioration including pitting, visible external cracks", methods: ["VT"], critical: true },
        { id: "tdy23", description: "Inspect pin box and sub pins for wear and damage — carry out NDT for threaded connection of stem and load collar area", methods: ["VT", "NDT"], critical: true, ndt: true },
      ]},
      { id: "tdy_misc", name: "Yearly — Dolly, elevator links & motors", items: [
        { id: "tdy30", description: "Entire visual inspection of torque tube / guide rails and related equipment as applicable", methods: ["VT"] },
        { id: "tdy31", description: "Entire visual inspection of Top Drive dolly — may include NDT of critical areas", methods: ["VT", "NDT"] },
        { id: "tdy32", description: "Inspect gearbox lubrication pump assembly for wear and damage if applicable", methods: ["VT"] },
        { id: "tdy33", description: "Measure and inspect elevator links", methods: ["Dim"], measurement: true, unit: "mm", critical: true },
        { id: "tdy34", description: "Carry out NDT inspection of critical areas of primary-load-carrying components", methods: ["NDT", "MPI", "UT"], critical: true, ndt: true },
        { id: "tdy35", description: "Inspect blower motors — impeller, fan, spark arrestors, louvers", methods: ["VT"] },
        { id: "tdy36", description: "Replace encoder belt as applicable", methods: ["VT"] },
      ]},
    ],
    td_ibop: [
      { id: "tdi_main", name: "Yearly — IBOP recertification (Cat IV)", items: [
        { id: "tdi1", description: "IBOP due for major inspection and recertification", methods: ["Doc"], critical: true },
        { id: "tdi2", description: "Exchange the IBOP with a certified unit", methods: ["Doc", "VT"], critical: true },
        { id: "tdi3", description: "Scope of work for recertification / exchange determined by condition and inspection results in consultation with Technical Authority", methods: ["Doc"], critical: true },
        { id: "tdi4", description: "Recertification / overhaul performed per §9 — repair, remanufacture, exchange", methods: ["Doc"] },
      ]},
    ],
    td_5yearly: [
      { id: "td5_main", name: "5-yearly / 15,000 hrs — Major overhaul (Cat IV)", items: [
        { id: "td5y1", description: "Equipment due for major inspection and recertification per API RP 8B", methods: ["Doc"], critical: true },
        { id: "td5y2", description: "Scope of work for recertification / exchange determined by condition and inspection results in consultation with Technical Authority", methods: ["Doc"], critical: true },
        { id: "td5y3", description: "Recertification / overhaul performed per §9 — repair, remanufacture, exchange of components", methods: ["Doc", "VT"] },
        { id: "td5y4", description: "Verify interval basis: 5-yearly OR 15,000 operating hours (max 7 years) — document which basis applies and verify hour-service-meter reading in CMMS", methods: ["Doc"], critical: true },
      ]},
    ],
  },
};
