services:
  # Backend API
  - type: web
    name: cmms-erp-backend
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: cmms-erp-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_TOKEN_EXPIRY
        value: 15m
      - key: JWT_REFRESH_TOKEN_EXPIRY
        value: 7d
      - key: CORS_ORIGIN
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: OPENAI_API_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false

databases:
  - name: cmms-erp-db
    databaseName: cmms_erp
    user: cmms_user
    region: frankfurt
    plan: free
